# Generated by Django 4.1.7 on 2023-11-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyGoMart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlist',
            old_name='cartID',
            new_name='itemNo',
        ),
    ]
